# Generated by Django 2.0.2 on 2019-04-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('sku', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('flag', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
